### ISSUE TITLE
[Bug] Remaining 8KB fill cannot be cleared

### ISSUE THREAD

**Issue by diday9** [tompee26/Fill-Device-Disk#3]
Description: Upon clearing the fill, there is a remaining 8KB that cannot be cleared. See screenshot for reference
![screenshot_2016-10-18-09-31-11](https://cloud.githubusercontent.com/assets/13597887/19460358/d975f974-9515-11e6-89cf-b0ae4465e923.png)

Steps to Reproduce:
1. Open app
2. Perform Easy Fill
3. Clear fill
4. Check "Fill" amount

Result: There is remaining 8KB

Expected: Fill should be empty after clear

**Comment by tompee26** [comment]
This is expected. Since build is debug, dex files are present in files directory. This should be ok in release build,
